#+startup: overview indent

* Comentários em 09/05 às 12:30
** Introdução
No final do penúltimo parágrafo, mencionar que é este problema
específico que é trazido como motivador para realizar este trabalho,
ou seja, pretende-se estudar se ferramentas de bigdata permitem a
aceleração do framework starvz. Nota que ainda que o objetivo seja
antecipado (pois há uma seção específica para isso), já prepara o
leitor do que esta por vir, o objetivo geral.

No final, na estrutura do documento, remover o itemize e colocar a
descrição de cada Seção em uma frase. Acredito que seja um estilo
melhor para a leitura.
** Fundamentação teórica
Remover o itemize do parágrafo de abertura. Colocar o texto na forma
corrida com uma frase por item. Preocupar-se em encadear as ideais.

No final, ao referenciar a Fig 2.1, remover os parênteses e colocar
"conforme podemos observar na Figura 2.1". Explicar os elementos da
figura, dizendo por exemplo de que são feitas as ferramentas, o que
especificamente cada uma faz.
** Objetivos
- [ ] Remover "Objetivo Principal"
** Cronograma

Em função da sugestão dos coordenadores do curso, adicionar na tabela
e a descrição respectiva no texto os seguintes itens:
 - Revisão bibliográfica sobre o assunto x
 - Coleta e preparação dos dados
 - Definição da melhor alternativa/ferramenta para y
 - Realização de experimentos e análise de resultados

Citar a Tabela (que foi marcada com um \label antes do \caption) com
\ref no texto. Transformar o itemize do cronograma em texto corrido,
colocando uma frase por cada item do cronograma detalhando o que foi
feito.

* Comentários em 07/05 às 14:30
** Geral
- Substituir \legend por \caption, que é o comando correto para
  legendas de figuras, tabelas, etc.
- R:Não havia colocado \caption pois ele vem com um número de seção
  (e.g. Figura 5.1) como nada tem numeração, achei mais coerente
  seguir o padrão, mas troquei para caption (caso ache que
  fique melhor da outra forma, avisa que eu troco de novo).

** Introdução
- Algumas passagens precisariam de ajustes, mas okay para uma versão
  de proposta (depois reveremos para o documento final).
- R:Ok

- No final, dizer que o documento é uma proposta e está estruturado
  assim: ...
- R: Ok

- Remover "tênues"
- R: Ok

** Fundamentos teóricos (Trabs. Relacionados)
- Colocar figura pequena no final em StarVZ com as duas fases.
- R: Ok
** Objetivos
- Na figura em objetivos, a saída do R não são arquivos FXT mas
  arquivos FEATHER. Talvez tenhamos que rever o uso de FEATHER e
  passar a usar outro formato colunar, como o PARQUET do arrow.
  Mas de fato, o uso de arquivos CSV pode auxiliar a carga no HDFS.
  O FEATHER (ou ARROW) poderiam ser usados depois da fase 1,
  mas teríamos que alterar o início da fase 2 para ler do HDFS.
- R1:FXT estava por erro de copy-paste, corrigido.
- R2:Acho interessante o fato de podermos mudar o formato da saída.
  Talvez fazer isso parametrizável, se o usuário tiver infra ele
  pode processar tudo em spark/hdfs, caso contrário, segue o fluxo
  normal. Minha sugestão é fazer isso como um extra caso tenha
  tempo durante o trabalho, caso contrário elencar para
  trabalhos futuros, o que acha?

  #+BEGIN_COMMENT
  Acho uma ideia interessante para explorar como um extra. Penso que o
  que está descrito já consiste em um trabalho experimental e de
  implementação consistente. Sendo assim, penso que esse trabalho
  extra de testar outros formatos possa não ser explicitado na
  proposta (pois vira promessa) e seja feito caso dê tempo.
  #+END_COMMENT

** Metodologia
- Experimentações -> experimentos
- R: Ok
** Cronograma okay
